Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -51,6 +51,9 @@ jobs:
 
             cd "$repo_name" || { echo "Failed to enter directory $repo_name"; cd ..; rm -rf "$repo_name"; continue; }
 
+            # Configure Git to use the GitHub token for authentication
+            git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
+
             # Fetch all branches
             git fetch --all
 
@@ -132,10 +135,9 @@ jobs:
             git commit -m "Copy Tekton files from $PREV_BRANCH to $latest_branch"
 
             # Push changes to the respective repository
-            push_url="${repo_url}"
-            echo "Pushing changes to $push_url"
-            if ! git push "$push_url" "$latest_branch"; then
-              echo "Failed to push changes to $push_url"
+            echo "Pushing changes to $repo_url"
+            if ! git push origin "$latest_branch"; then
+              echo "Failed to push changes to $repo_url"
             fi
 
             # Clean up for the next repository
