Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -120,9 +120,21 @@ jobs:
                 sed -i "/pipelinesascode.tekton.dev\/on-cel-expression:/{
                   n; s/\(target_branch[[:space:]]*==[[:space:]]*\"$new_rhoai\"\)/\1 && !\"bundle\/manifests\/rhods-operator.clusterserviceversion.yml\".pathChanged()/
                 }" "$new_file_name"
+            
+                # Ensure condition is added for pull_request events if it's not already present
+                if ! grep -q "&& !\"bundle/manifests/rhods-operator.clusterserviceversion.yml\".pathChanged()" "$new_file_name"; then
+                  sed -i "/pipelinesascode.tekton.dev\/on-cel-expression:/{
+                    n; s/\(target_branch[[:space:]]*==[[:space:]]*\"$new_rhoai\"\)/\1 && !\"bundle\/manifests\/rhods-operator.clusterserviceversion.yml\".pathChanged()/
+                  }" "$new_file_name"
+                  echo "Added missing condition for $new_rhoai in $new_file_name."
+                else
+                  echo "Condition already exists for $new_rhoai in $new_file_name."
+                fi
+            
                 echo "Updated pipelinesascode.tekton.dev/on-cel-expression in $new_file_name"
               fi
             done
+
 
 
             # Check out the latest branch
